version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: vault_user
      POSTGRES_PASSWORD: vault_pass
      POSTGRES_DB: vault_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vault_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: hashicorp/vault:1.15
    container_name: vault-server
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-vault-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data:
