spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/appdb
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true